export const SESSION_STATE_KEY = 'lsShadowingState';
export const SESSION_PANEL_BOOTING_KEY = 'lsPanelBootingForPractice';
export const SESSION_SUBTITLE_HINT_KEY = 'lsSubtitleFetchHint';
export const SESSION_SUBTITLE_SOURCE_KEY = 'lsSubtitleSource';
export const SESSION_REQUEST_LANGUAGE_SETUP_KEY = 'lsRequestLanguageSetup';
export const STORAGE_KEY_WATCH_PRACTICE_ACTIVE = 'lsWatchPracticeActive';
export const STORAGE_KEY_PENDING_UPDATE = 'lsPendingUpdateVersion';

export const SETTINGS_KEYS = [
  'nativeLanguage',
  'targetLanguage',
  'repetitionCount',
  'pauseDuration',
  'subtitleDisplayMode',
  'interfaceTheme'
];

export const CONTENT_COMMAND = {
  PLAY_NATIVE: 'LS_PLAY_NATIVE',
  REPEAT_SEGMENT: 'LS_REPEAT_SEGMENT',
  NEXT_SENTENCE: 'LS_NEXT_SENTENCE',
  PREV_SENTENCE: 'LS_PREV_SENTENCE',
  PAUSE_FOR_RECORDING: 'LS_PAUSE_FOR_RECORDING',
  AB_SET_A: 'LS_AB_SET_A',
  AB_SET_B: 'LS_AB_SET_B',
  AB_TOGGLE_LOOP: 'LS_AB_TOGGLE_LOOP',
  AB_CLEAR: 'LS_AB_CLEAR',
  SEEK_CUE: 'LS_SEEK_CUE',
  OPEN_LANGUAGE_SETTINGS: 'OPEN_LANGUAGE_SETTINGS',
  OPEN_HELP: 'OPEN_HELP'
};

export const RUNTIME_MESSAGE = {
  OPEN_SIDE_PANEL: 'LS_OPEN_SIDE_PANEL',
  CLOSE_SIDE_PANEL: 'LS_CLOSE_SIDE_PANEL',
  LEFT_YOUTUBE: 'LS_LEFT_YOUTUBE',
  REQUEST_SESSION_PUSH: 'LS_REQUEST_SESSION_PUSH',
  RELAY_SESSION_PUSH: 'LS_RELAY_SESSION_PUSH',
  REGISTER_SIDE_PANEL_TAB: 'LS_REGISTER_SIDE_PANEL_TAB',
  RELAY_TO_YOUTUBE_TAB: 'LS_RELAY_TO_YOUTUBE_TAB'
};

export const WORKER_API_BASE = 'http://127.0.0.1:8000';
export const MANAGER_API_BASE = 'http://127.0.0.1:8765';

export const DEFAULT_REPETITION_COUNT = 1;
export const DEFAULT_PAUSE_DURATION = 'auto';
export const DEFAULT_SUBTITLE_DISPLAY_MODE = 'both';
export const MAX_RECORDING_MS = 30000;
